#!/bin/bash

# Usage: ./tmux-init -s [session-name] -s [repo-subdirectory]
# if no session name provided, uses "dev" as default
# if no repo subdirectory provided, uses ~/repos

SESSION_NAME="dev"
REPO_SUBDIR=""

while getopts "s:d:" opt; do
    case $opt in
        s) SESSION_NAME="$OPTARG" ;;
        d) REPO_SUBDIR="$OPTARG" ;;
    esac
done

if [ -z "REPO_SUBDIR" ]; then
    TARGET_DIR=~/repos
else
    TARGET_DIR=~/repos/$REPO_SUBDIR
fi

# create new session
tmux new-session -d -s "$SESSION_NAME" -c "$TARGET_DIR"

# setup first window
tmux rename-window -t "$SESSION_NAME:0" src
tmux split-window -h -t "$SESSION_NAME:0" -c "$TARGET_DIR"

# setup second window with three panes
tmux new-window -t "$SESSION_NAME" -n build/debug -c "$TARGET_DIR"
tmux split-window -h -t "$SESSION_NAME:1" -c "$TARGET_DIR"
tmux select-pane -t "$SESSION_NAME:1.0"
tmux resize-pane -t "$SESSION_NAME:1.0" -R 50
tmux select-pane -t "$SESSION_NAME:1.1"
tmux split-window -v -t "$SESSION_NAME:1.1" -c "$TARGET_DIR"
tmux resize-pane -t "$SESSION_NAME:1.2" -D 25

# select the first window to start
tmux select-window -t "$SESSION_NAME:0"

# attach to session
tmux attach-session -t "$SESSION_NAME"
